### ISSUE TITLE
モバイル版webデザイン

### ISSUE THREAD

**Issue by sinagaki58** [Tink-inc/design#1]
# Top

![image](https://cloud.githubusercontent.com/assets/11718183/19472317/c2d395f4-9561-11e6-9be4-9d636e8cae39.png)

ver2
![image](https://cloud.githubusercontent.com/assets/11718183/19587448/5e82ef70-9799-11e6-93b9-92f8b169004e.png)

**Comment by sinagaki58** [comment]
# 商品詳細

## v1 
![image](https://cloud.githubusercontent.com/assets/11718183/19472374/07359300-9562-11e6-8e70-26aff26719b3.png)

## v2
![image](https://cloud.githubusercontent.com/assets/11718183/19472379/0b527eb2-9562-11e6-88db-ae4c1df9d7d7.png)

**Comment by sinagaki58** [comment]
test

**Comment by rayray-py** [comment]
てすと

**Comment by sinagaki58** [comment]
商品説明に
発売日、カテゴリ、容量を追加。

![image](https://cloud.githubusercontent.com/assets/11718183/19472702/3e5f5ee6-9563-11e6-86f0-330b499e35db.png)

**Comment by sinagaki58** [comment]
- FAB追加
- 価格の位置調整

![image](https://cloud.githubusercontent.com/assets/11718183/19473358/45d74712-9566-11e6-8d09-daf263f56b35.png)

**Comment by sinagaki58** [comment]
## 投稿画面
- レート
- 使用期間
- 良い点
- 悪い点

![image](https://cloud.githubusercontent.com/assets/11718183/19509853/a632a3ee-961b-11e6-8e25-3542c13786d2.png)

**Comment by sinagaki58** [comment]
## mypage

![image](https://cloud.githubusercontent.com/assets/11718183/19548295/b0dba54e-96d8-11e6-8795-77cc8061d0da.png)

**Comment by sinagaki58** [comment]
## login 

![image](https://cloud.githubusercontent.com/assets/11718183/19548305/b9e1c484-96d8-11e6-9bf6-60289166b02c.png)

**Comment by sinagaki58** [comment]
## ユーザー入力画面

![image](https://cloud.githubusercontent.com/assets/11718183/19553696/36bb5e9a-96f0-11e6-86b5-16491e912c64.png)

**Comment by sinagaki58** [comment]
## sign_up

![image](https://cloud.githubusercontent.com/assets/11718183/19553702/408edfd2-96f0-11e6-9d95-28bf913a77dc.png)

**Comment by rayray-py** [comment]
そういえばお問い合わせ・ご要望ボタンを付けたい
やっぱりハンバーガーメニューは導入せざるを得ないのかな…

**Comment by sinagaki58** [comment]
フッターにまとめる案

![image](https://cloud.githubusercontent.com/assets/11718183/19582563/86e3dde0-9770-11e6-9303-ecfd0f4faf98.png)

**Comment by sinagaki58** [comment]
## 成分一覧


![image](https://cloud.githubusercontent.com/assets/11718183/19594588/a9c9c838-97c0-11e6-8603-e237d833366b.png)

![image](https://cloud.githubusercontent.com/assets/11718183/19594602/af1d9710-97c0-11e6-81f6-be887b9fe56e.png)

**Comment by sinagaki58** [comment]
close #1
